apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: g0dkh9v5v-nodejs-gitops
  description: This is GitOps manifest for g0dkh9v5v-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=g0dkh9v5v-nodejs
    backstage.io/kubernetes-id: g0dkh9v5v-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: g0dkh9v5v-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:g0dkh9v5v-nodejs
